# Generated by Django 2.2.11 on 2020-03-14 13:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import recording.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('keyname', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('channel_type', models.CharField(choices=[('radio', 'Radio'), ('tv', 'TV')], max_length=16)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('path', models.FileField(upload_to=recording.models.recordings_directory)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recording.Channel')),
            ],
        ),
    ]
