# Generated by Django 2.2.11 on 2020-03-14 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0002_recording_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='recording',
            options={'ordering': ('channel', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('name', 'keyname')},
        ),
        migrations.AlterUniqueTogether(
            name='recording',
            unique_together={('channel', 'filename')},
        ),
    ]
