# Generated by Django 2.2.11 on 2020-03-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0003_auto_20200314_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='path',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='recording',
            unique_together={('channel', 'path')},
        ),
        migrations.RemoveField(
            model_name='recording',
            name='filename',
        ),
    ]
