# Generated by Django 2.2.11 on 2020-03-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0004_auto_20200318_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
