# Generated by Django 2.2.11 on 2020-03-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0005_channel_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='updated',
        ),
    ]
