# Generated by Django 2.2.11 on 2020-03-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0006_remove_channel_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recording.Channel'),
        ),
    ]
